#!/usr/bin/env ruby
# encoding: UTF-8

Dir.chdir '/Users/2Be/Ruby/plezi/plezi/'

require 'benchmark'
require "bundler/setup"
require "plezi"

# You can add fixtures and/or initialization code here to make experimenting
# with your gem easier. You can also use a different console, if you like.

# (If you use this, don't forget to add pry to your Gemfile!)
# require "pry"
# Pry.start

require "irb"
IRB.start
