#!/usr/bin/env ruby
# encoding: UTF-8

$LOAD_PATH.unshift File.expand_path(File.join('..', '..', 'lib'), __FILE__ )
require "plezi"

Iodine.logger = nil

HELLO = 'Hello Plezi'
Plezi.route('*') { HELLO }

# ab -n 10000 -c 200 -k http://127.0.0.1:3000/
# ~/ruby/wrk/wrk -c400 -d10 -t12 http://localhost:3000/
