source "https://rubygems.org"

####################
# core gems

# include the basic anorexic framework and server
gem 'anorexic'

####################
# development gems

# use pry gem for basic debug ( put `binding.pry` at breake point )?
# gem 'pry'


# active support can run without rails and extends the Ruby language.
# it might be heavy, be warned.
# see: http://guides.rubyonrails.org/active_support_core_extensions.html
# 
# gem 'activesupport', :require => ['active_support', 'active_support/core_ext'] 
# or:
# gem 'activesupport', :require => ['active_support', active_support/all'] 


####################
# gems for easy markup

## erb for HTML fanatics:
# gem 'erb'

## Slim is great - we like the name as well ;) :
# gem 'slim'

## we love Haml, even though it can be slow:
# gem 'haml'

## we love Sass
# gem "sass"

## and maybe coffee script? (although, we just use javascript, really)
# gem "coffee-script"

## we also like I18n:
# gem 'i18n'

####################
# gems for databases and models

## if you want to use a database, here are a two common enough options:
# gem 'sqlite3'
# gem 'pg'

## someone told me good things about sequel:
## http://sequel.jeremyevans.net/rdoc/files/README_rdoc.html
## http://sequel.jeremyevans.net/rdoc/files/doc/cheat_sheet_rdoc.html
## this seems greate, but we left out any auto-config for this one... seems to work out of the box.
# gem 'sequel'

## if you want to use ActiveRecord, uncomment the following line(s)...
## but first, please remember that AcriveRecord has known issues with multiple threads.
# gem 'activerecord', :require => 'active_record'
# gem 'bcrypt', '~> 3.1.7'
